name = "skipWhenMissingDependencies Crash"
author = "DartRuffian"
prefix = "swmd"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp"
]
exclude = []

[properties]
author = "DartRuffian"